### ISSUE TITLE
YouTube : Without channel logo and video title.

### ISSUE THREAD

**Issue by SCP-017** [dieghernan/chulapa#11]
**Is your feature request related to a problem? Please describe.**

I just want a clean YouTube Video embedded with lazy YouTube video loading.

---

**Describe the solution you'd like**

I found a repo that applies that feature and it looks neat too.

---

**Describe alternatives you've considered**

Applying the code used in there

---

**Additional context**

The repo link :
https://github.com/alfurka/jekyll-embed-youtube-lazy-load

**Comment by dieghernan** [comment]
Hi,

Just for me to understand, have you checked https://dieghernan.github.io/chulapa/docs/04-layouts#video-support ?

Do you see material improvements of https://github.com/alfurka/jekyll-embed-youtube-lazy-load vs. the current implementation?

I had a look (see https://dieghernan.github.io/remote/demo/10-a-video) and does not seem difficult, however there is a lot to polish on the style / css side.

Best,

**Comment by SCP-017** [comment]
1. Yes, I've already checked that.
2. Yes, the current Chulapa implementation has a fine material improvements than the other one.
3. I already had a look, I'm not a dev so I can't really explain this but is it possible to make another implementation of your current ones but without the YouTube Channel logo and the video title? Just a video with a "play" button? Just like in the repo I've mentioned, a video with just a play button.

I know it's too much for me to ask this but can you please consider my request?

I'm thinking of embedding a YouTube video in my site but I want it to look more simple so my site visitors can see the video preview clearly in the mobile view. (Desktop view doesn't have a problem with this because of the large screen.😅)

**Comment by dieghernan** [comment]
I would have a look and come back to you (hopefully) in a couple of weeks

**Comment by dieghernan** [comment]
Hi @SCP-017 

It is already implemented as a new snippet. Instead of :

```
{% include snippets/video.html id="your_youtube_id" provider="youtube" %}
```

Use

```
{% include snippets/youtube.html id="your_youtube_id" %}
```

Some demos:

- Docs: https://dieghernan.github.io/chulapa/docs/04-layouts#experimental-deferred-lazy-loading-of-youtube-videos
- Demo 1: https://dieghernan.github.io/remote/demo/10-a-video
- Demo 2: https://dieghernan.github.io/remote/demo/11-demo-youtube-lazy

**Comment by SCP-017** [comment]
I'm ver grateful that you've granted my selfish request. Now the video preview is clearly visible and it loads faster too because of the lazy loading.

I think I will close this issue now for it is already solved. Thank you.😃🖤
