### ISSUE TITLE
Collection Cards should follow the applied theme.

### ISSUE THREAD

**Issue by SCP-017** [dieghernan/chulapa#19]
**Is your feature request related to a problem?**

The collection cards should follow the applied theme.

---

**Describe the solution you'd like**

The card layout of a collection should follow the applied theme, instead it is still displayed in white background and the title and date doesn't really stand out from the white background so it's not quite visible.

---

**Additional context**

Collection Cards background screenshot:

![Screenshot_2022-12-01-08-41-12-763_org bromite bromite](https://user-images.githubusercontent.com/112224835/204939855-9fc9c1fb-09f9-40ec-8360-9dded68c9544.jpg)

**Comment by dieghernan** [comment]
Thanks, that’s was an issue with the setup of that specific skins. You should see the changes the next time you build your site

**Comment by dieghernan** [comment]
See a preview 

https://dieghernan.github.io/SCP-017.github.io/pages/index.pages/my.posts.html
